Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 242, in <lambda>
    command=lambda: run_tkinter_RFCcheck())
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 187, in run_tkinter_RFCcheck
    canvas.create_window(20, 170, width=960, height=30, window=select_entry, anchor=W)
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 2814, in create_window
    return self._create('window', args, kw)
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 2776, in _create
    return self.tk.getint(self.tk.call(
_tkinter.TclError: can't use .!entry in a window item of this canvas
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 280, in <module>
    run_tkinter_root()
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 253, in run_tkinter_root
    root.mainloop()
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
