Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 241, in <lambda>
    command=lambda: run_tkinter_RFCcheck())
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 190, in run_tkinter_RFCcheck
    canvas.create_window(500, 120, window=select_model_button)
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 2814, in create_window
    return self._create('window', args, kw)
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 2776, in _create
    return self.tk.getint(self.tk.call(
_tkinter.TclError: can't use .!button in a window item of this canvas
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 279, in <module>
    # 运行主窗口
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 252, in run_tkinter_root
    
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
